### ISSUE TITLE
Проверка HW

### ISSUE THREAD

**Issue by smirnovdevel** [goliksim/Ya-Tasks#3]
Проблема с зависимостями пакета test_api. Прежде чем запустить, пришлось корректировать pubspec.yaml
Далее, в корне отсутствует файл l10n.yaml. Может он в gitignore добавлен. Добавил, далее пришлось по всему тесту расставлять ! в строчках - null safety - AppLocalizations.of(context)!.priority.
По сути, приложение не работает. Что-то надо исправить, что-то дописать. 
dart fix - 26 исправлений

pref.setString('log', finalDateString + text);
Зачем писать логи в шаред? Тем более в этом этапе домашки.

>  **Чистота кода и общая структура проекта (max 5 баллов)**

 - Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (+1 балл) +1

 - Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (+1 балл) 0, очень много необработанных предупреждений

 - Форматирование кода присутствует (+1 балл) +1
 
 - Код разбит на фичи и слои (не важно, feature-first / layer-first) (+2 балла) +2

>  **Навигация, UI, animations (max 8 баллов)**

 - Навигация инкапсулирована в отдельной сущности, отсутствуют явные переходы (+1 балл) +1

 - Текст длинных заметок обрезается по макету (+1 балл) +1

 - Поддержка ночной темы (+1 балл) +1

 - Реализованы анимации для добавления/исчезновения/редактирования и прочих взаимодействий с заметками (+1 балл) 0 в скачанной apk анимаций нет или настроены неверно

 - Реализована поддержка лендскейп-ориентации (+2 балла) +1 AppBar сжат, это хорошо, но неплохо было бы сохранить вывод количества выполненных задач

 - Реализована поддержка больших экранов (планшеты) (+2 балла) +1 Размеры шрифтом можно было адаптировать, остаются такими же. Паддинги так же, верстку больших экранов делают "резиновой"

>  **Firebase (max 3 балла)**

 - Реализована работа с Remote Configs, работает рантайм-переключение цвета важности (дефолтный красный по Фигме vs     #793cd8) (+2 балла) 0 не работает в рантайме

 - К проекту подключён и настроен Firebase Crashlytics, репортинг ошибок работает (+1 балл) 0

static Future<void> _initFirebase() async {
    await Firebase.initializeApp(
        //options: DefaultFirebaseOptions.currentPlatform,
        );
    Logs.logIns.writeLog('Firebase initialized!');
    _initCrashlytics();
  }

>  **Build & Release (max 8 баллов)**

 - Поддержаны 2 флейвора: для сборки тестинг и прод окружения. Различие реализовать визуально: наличием шильдика DEV (+2 балла) +2

 - Настроен CI на GitHub, Есть распространение через какой-то сервис. 0 баллов. В гите нет Gig Action. Распространение подразумевалось именно через CI

>  ** Разное (max 2 балла)**

 - Добавлен инструмент для аналитики: Firebase/AppMetrica. Собирается аналитика по событиям: добавление, удаление, выполнение, переходы по экранам (+1 балла) +1 Только за то, что есть в коде

 - Для дата-моделей используется пакет freezed (+1 балл) +1 Я бы больше поставил. Представляю чего стоило сделать микс из freezed и Hive. 

ps. Repository Structure.md понравился.  Если есть вопросы, моя телега @Smirnov_devel

> **ИТОГО: 13/26**

**Comment by goliksim** [comment]
@smirnovdevel Привет, спасибо за проверку.
- Вероятнее всего все линторы, что у тебя высвечивались из-за моей старой версии Flutter. У меня все было по 0лям. Мне уже писали об этом, руки не дошли обновится. **Если скачать apk, все работает!**
- `l10n.yaml` нет, так как я в ручную запускал `flutter gen-l10n`
- Логи изначально писал в файл через `path_provider`, но чтобы работало в вебе стал писать в шаред. Понимаю что странно, но меня устраивало)
- Не совсем понял в чем проблема с крашлитикой. Если бросать ошибки через throw, они отправляются в firebase.

**Comment by smirnovdevel** [comment]
Привет. По поводу линтеров, я бы даже не смотрел, что у меня в ide выдает, если бы были пройденные тесты в git actions. По поводу версий вполне допускаю.  По поводу крешлитики, по крайней мере в версии на гите, инициализация с настройками заремарена. //options: DefaultFirebaseOptions.currentPlatform. Другой инициализации я не увидел. Если она есть, без проблем, пересмотрю оценку. Просто не представляю, как проиниализировать без id и т.п.

**Comment by goliksim** [comment]
@smirnovdevel Ааа, закомментил фичу и забыл раскомментить)
Все файлики конфигурации на месте (`firebase_options.dart`, `google-services.json` ...)
Скрины с крашлитики в md я не фотошопил, краши приходят)
![image](https://github.com/goliksim/YaFlutter/assets/66952748/d3cc8f45-b4da-4f4c-b607-dd01f39227b6)

**Comment by smirnovdevel** [comment]
@goliksim Да я и не думаю что ты будешь фотошопить,  давай я завтра с ментором посоветуюсь, как в твоём случае быть. А нафига ты его комментил ?

**Comment by smirnovdevel** [comment]
@goliksim upd. По линтеру +1, допускаю что различие версий сказывается, по крешлитике +1. Но так-то согласись, косяк запушить неработающую фичу. 

ИТОГО: 15/26

**Comment by PhilipPeric** [comment]
@goliksim привет) у меня экран смерти при запуске dev flavor
вот так пытался 
flutter run -t lib/main_dev.dart  --flavor=dev
я все правильно делаю? можешь у себя чекнуть?

fyi prod ок запускается

![Screenshot_20230720_171151](https://github.com/goliksim/YaFlutter/assets/35840908/4d9d9641-75fb-43f3-bae5-7ba367e5698f)

**Comment by goliksim** [comment]
@PhilipPeric Привет, я дурачок просто
https://github.com/goliksim/YaFlutter/blob/9812a0d50f244ff44abfb1ca6f489aafebc60ffa/ya_todolist/lib/main.dart#L9
https://github.com/goliksim/YaFlutter/blob/9812a0d50f244ff44abfb1ca6f489aafebc60ffa/ya_todolist/lib/main_dev.dart#L9
Добавьте перед локатором `await`. Пока добавлял firebase не уследил за флейворами, не судите строго 😥

**Comment by PhilipPeric** [comment]
### Чистота кода и общая структура проекта (max 5 баллов)

Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов 1/1

Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (0/1, пара неиспользуемых импортов + // ignore: sized_box_for_whitespace в task_widget.dart

Форматирование кода присутствует 1/1

Код разбит на фичи и слои (не важно, feature-first / layer-first) 2/2

### Навигация, UI, animations (max 8 баллов)

Навигация инкапсулирована в отдельной сущности, отсутствуют явные переходы 1/1

Текст длинных заметок обрезается по макету 1/1

Поддержка ночной темы 1/1

Реализованы анимации для добавления/исчезновения/редактирования и прочих взаимодействий с заметками 0/1 смотрел в эмуляторе, ничего не увидел 🤷‍♂️ или подскажи как потестить 

Реализована поддержка лендскейп-ориентации 1/2 см скриншот
![Screenshot_20230720_172134](https://github.com/goliksim/YaFlutter/assets/35840908/8cf1977a-66a6-47cf-b4b5-6b7574ca4bd1)


Реализована поддержка больших экранов (планшеты) 2/2

### Firebase (max 3 балла)

Реализована работа с Remote Configs, работает рантайм-переключение цвета важности (дефолтный красный по Фигме vs #793cd8) 1/2

К проекту подключён и настроен Firebase Crashlytics, репортинг ошибок работает 1/1

### Build & Release (max 8 баллов)

Поддержаны 2 флейвора: для сборки тестинг и прод окружения. Различие реализовать визуально: наличием шильдика DEV 2/2 завелось в итоге, шильдик/иконки отличаются

Настроен CI на GitHub, Есть распространение через какой-то сервис. 0/4

Есть распространение через какой-то сервис вроде Firebase App Distribution 2/2 а ты типа ручками апкшку загрузил в fad? спрошу еще ментора ок ли что не из github actions деплоится и засчитывается ли в таком случае

### Разное (max 2 балла)

Добавлен инструмент для аналитики: Firebase/AppMetrica. Собирается аналитика по событиям: добавление, удаление, выполнение, переходы по экранам 1/1

Для дата-моделей используется пакет freezed 1/1

### итого пока 18 / 26
